### ISSUE TITLE
It doesn't work bruh!

### ISSUE THREAD

**Issue by MrWelch99** [amberkakkar01/Magic-Ball#1]
Random() generates a number between 0 and 1. You multiply it by 10, add 1 and you get a maximum of 11. You have option in you switch case that aren't being reached.

**Comment by amberkakkar01** [comment]
Yass! some cases may be unreachable but the code is absolutely fine. It is working
![opop](https://user-images.githubusercontent.com/52875602/117528648-cd852900-aff0-11eb-9114-853c74d64dca.PNG)
